export const EMPLOYEE_CREATE_REQUEST = "EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL = "EMPLOYEE_CREATE_FAIL";

export const EMPLOYEE_GET_ALL_REQUEST = "EMPLOYEE_GET_ALL_REQUEST";
export const EMPLOYEE_GET_ALL_SUCCESS = "EMPLOYEE_GET_ALL_SUCCESS";
export const EMPLOYEE_GET_ALL_FAIL = "EMPLOYEE_GET_ALL_FAIL";

export const EMPLOYEE_GET_REQUEST = "EMPLOYEE_GET_REQUEST";
export const EMPLOYEE_GET_SUCCESS = "EMPLOYEE_GET_SUCCESS";
export const EMPLOYEE_GET_FAIL = "EMPLOYEE_GET_FAIL";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL = "EMPLOYEE_UPDATE_FAIL";

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

export const EMPLOYEE_DELETE_BY_ID_REQUEST = "EMPLOYEE_DELETE_BY_ID_REQUEST";
export const EMPLOYEE_DELETE_BY_ID_SUCCESS = "EMPLOYEE_DELETE_BY_ID_SUCCESS";
export const EMPLOYEE_DELETE_BY_ID_FAIL = "EMPLOYEE_DELETE_BY_ID_FAIL";

export const EMPLOYEE_ALL_REQUEST = "EMPLOYEE_ALL_REQUEST";
export const EMPLOYEE_ALL_SUCCESS = "EMPLOYEE_ALL_SUCCESS";
export const EMPLOYEE_ALL_FAIL = "EMPLOYEE_ALL_FAIL";

export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAIL = "EMPLOYEE_DETAILS_FAIL";




