export const RESTAURANT_LIST_REQUEST = "RESTAURANT_LIST_REQUEST";
export const RESTAURANT_LIST_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_LIST_FAIL = "RESTAURANT_LIST_FAIL";

export const RESTAURANT_CREATE_REQUEST = "RESTAURANT_CREATE_REQUEST";
export const RESTAURANT_CREATE_SUCCESS = "RESTAURANT_CREATE_SUCCESS";
export const RESTAURANT_CREATE_FAIL = "RESTAURANT_CREATE_FAIL";

export const RESTAURANT_DETAILS_REQUEST = "RESTAURANT_DETAILS_REQUEST";
export const RESTAURANT_DETAILS_SUCCESS = "RESTAURANT_DETAILS_SUCCESS";
export const RESTAURANT_DETAILS_FAIL = "RESTAURANT_DETAILS_FAIL";

export const RESTAURANT_UPDATE_REQUEST = "RESTAURANT_UPDATE_REQUEST";
export const RESTAURANT_UPDATE_SUCCESS = "RESTAURANT_UPDATE_SUCCESS";
export const RESTAURANT_UPDATE_FAIL = "RESTAURANT_UPDATE_FAIL";

export const RESTAURANT_DELETE_REQUEST = "RESTAURANT_DELETE_REQUEST";
export const RESTAURANT_DELETE_SUCCESS = "RESTAURANT_DELETE_SUCCESS";
export const RESTAURANT_DELETE_FAIL = "RESTAURANT_DELETE_FAIL";

export const RESTAURANT_ALL_REQUEST = "RESTAURANT_ALL_REQUEST";
export const RESTAURANT_ALL_SUCCESS = "RESTAURANT_ALL_SUCCESS";
export const RESTAURANT_ALL_FAIL = "RESTAURANT_ALL_FAIL";
